<?php

/**
 * @file
 * Primary module hooks for Webinar Tweaks.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;
use \Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_entity_presave().
 */
function webinar_tweaks_entity_presave(EntityInterface $entity) {
  // Check if we are saving a 'webinar' node.
  if ($entity instanceof NodeInterface && $entity->bundle() === 'webinar') {
    $title = $entity->label();

    $fixed_title = \Drupal::service('webinar_tweaks.title_manager')->fixTitle($title);

    $entity->setTitle($fixed_title);
  }
}

/**
 * Implements hook_form_alter().
 */
function webinar_tweaks_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // We want to target BOTH the "Edit" form AND the "Add" form.
  // The IDs are: 'node_webinar_edit_form' and 'node_webinar_form'.
  if ($form_id === 'node_webinar_edit_form' || $form_id === 'node_webinar_form') {
    // Hide the promote checkbox.
    $form['promote']['#access'] = FALSE;

    // Attach our custom validation handler.
    $form['#validate'][] = 'webinar_tweaks_validate';
  }

  // Log the ID so you can see which one is being used.
  \Drupal::logger('webinar_tweaks')->info('Form ID: @id', ['@id' => $form_id]);
}

function webinar_tweaks_validate(&$form, FormStateInterface $form_state) {
  // 1. Get the raw array for the 'title' field.
  $title = $form_state->getValue(['title', 0, 'value']);

  // 3. Run the logic.
  if (strlen($title) < 5) {
    $form_state->setErrorByName('title', 'Title must be at least 5 characters long.');
  }
}